default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  timeout: 5000

development:
  <<: *default
  database: dungeonbuddies_development

test:
  <<: *default
  database: dungeonbuddies_test

production:
  <<: *default
  database: dungeonbuddies_production
  username: dungeonbuddies
  password: <%= ENV['DUNGEONBUDDIES_DATABASE_PASSWORD'] %>
